using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Muzzle : MonoBehaviour
{
    [SerializeField] GameObject bullet;
    [SerializeField] Transform shootPoint;
    [SerializeField] float ShootForce;
    [SerializeField] float ShootingTime;
    [SerializeField] float ReloadTime;
    [SerializeField] int MagazineSize;
    [SerializeField] int BulletPerTap;
    [SerializeField] bool ButtonHold;

    [SerializeField] LayerMask ignoreLayer;

    GameObject playerCam;

    int bulletsShot, bulletsLeft;
    bool Shooting, readyToShoot;
    public bool reloading;
    public bool allowInvoke = true;
    public Transform cameraTransform; // ã‚«ãƒ¡ãƒ©ã®Transformã‚’è¨­å®š
    public float rotationSpeed = 5f;
    // Start is called before the first frame update
    void Start()
    {
        playerCam = GameObject.Find("Main Camera");
        bulletsLeft = MagazineSize;
        readyToShoot = true;
    }

    // Update is called once per frame
    void Update()
    {
        InputHandler();
    }

    // ï¿½ï¿½ï¿½Íï¿½ï¿½ï¿½
    private void InputHandler()
    {
        // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Å‚ï¿½ï¿½é‚©ï¿½Ì“ï¿½ï¿½Í‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        if (ButtonHold)
        {
            Shooting = Input.GetMouseButton(0);
        }
        else
        {
            Shooting = Input.GetMouseButtonDown(0);
        }

        // ï¿½Å‚Ä‚ï¿½ï¿½Ô‚Ìƒ`ï¿½Fï¿½bï¿½N
        if (readyToShoot && Shooting && !reloading && bulletsLeft > 0)
        {
            bulletsShot = 0;
            Shoot();
        }

        // ï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½h
        if (Input.GetKeyDown(KeyCode.R) && bulletsLeft < MagazineSize && !reloading)
        {
            Reload();
        }
    }

    // ï¿½eï¿½ğ”­ï¿½
    private void Shoot()
    {
        readyToShoot = false;

        // ï¿½ï¿½Ê‚Ì’ï¿½ï¿½ï¿½ï¿½É”ï¿½Î‚ï¿½
        Ray ray = playerCam.GetComponent<Camera>().ViewportPointToRay(new Vector3(0.5f, 0.5f, 0.5f));
        RaycastHit hit;

        Vector3 targetPoint;
        if (Physics.Raycast(ray, out hit, 1000f, ~ignoreLayer))
        {
            targetPoint = hit.point;
        }
        else
        {
            targetPoint = ray.GetPoint(10);
        }

        GameObject newbullet = Instantiate(bullet, this.transform.position, Quaternion.identity); //ï¿½eï¿½ğ¶ï¿½
        Rigidbody bulletRigidbody = newbullet.GetComponent<Rigidbody>();
        bulletRigidbody.AddForce(this.transform.forward * ShootForce * 2); //ï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½Nï¿½^ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½É’eï¿½É—Í‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        Destroy(newbullet, 10); //10ï¿½bï¿½ï¿½É’eï¿½ï¿½ï¿½ï¿½ï¿½ï¿½

        bulletsLeft--;
        bulletsShot++;

        // ï¿½eï¿½Æ’eï¿½ÉŠÔŠuï¿½ï¿½ï¿½ó‚¯‚ï¿½
        if (allowInvoke)
        {
            Invoke("ResetShot", ShootingTime);
            allowInvoke = false;
        }
    }

    // ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½Ô‚É‚ï¿½ï¿½ï¿½
    private void ResetShot()
    {
        readyToShoot = true;
        allowInvoke = true;
    }

    // ï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½hï¿½Ìï¿½ï¿½ï¿½
    private void Reload()
    {
        reloading = true;
        Invoke(nameof(ReloadFinished), 1);
    }

    private void ReloadFinished()
    {
        bulletsLeft = MagazineSize;
        reloading = false;
    }
}
